trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Instalar pip'

  - script: |
      pip install -r requirements.txt
    displayName: 'Instalar dependencias'

  - script: |
      python test/test_calculadora.py
    displayName: 'Ejecutar pruebas'